# alembic/script.py.mako
"""add workspace upgrades, tier clarification and subdomain

Revision ID: 02e7f74b0b7e
Revises: 3b0b53044068
Create Date: 2026-04-15 16:24:18.475720
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "02e7f74b0b7e"
down_revision: Union[str, None] = "3b0b53044068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_records", sa.Column("workspace_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_payment_records_workspace_id"),
        "payment_records",
        ["workspace_id"],
        unique=False,
    )
    op.add_column("subscriptions", sa.Column("workspace_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_workspace_id"),
        "subscriptions",
        ["workspace_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column(
            "is_flagged", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("custom_query_timeout", sa.Integer(), nullable=True)
    )
    op.add_column("users", sa.Column("custom_max_rows", sa.Integer(), nullable=True))
    op.add_column(
        "workspaces", sa.Column("subdomain", sa.String(length=120), nullable=True)
    )
    
    # [CORRECTED] Inject server_default to satisfy the NOT NULL constraint on existing rows
    op.add_column(
        "workspaces", 
        sa.Column(
            "billing_tier", 
            sa.String(length=30), 
            server_default=sa.text("'explorer'"), 
            nullable=False
        )
    )
    
    op.create_index(
        op.f("ix_workspaces_subdomain"), "workspaces", ["subdomain"], unique=True
    )
    # ### end Alembic commands ###
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspaces_subdomain"), table_name="workspaces")
    op.drop_column("workspaces", "billing_tier")
    op.drop_column("workspaces", "subdomain")
    op.drop_column("users", "custom_max_rows")
    op.drop_column("users", "custom_query_timeout")
    op.drop_column("users", "is_flagged")
    op.drop_index(op.f("ix_subscriptions_workspace_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=True
    )
    op.drop_column("subscriptions", "workspace_id")
    op.drop_index(op.f("ix_payment_records_workspace_id"), table_name="payment_records")
    op.drop_column("payment_records", "workspace_id")
    # ### end Alembic commands ###
