# alembic/script.py.mako
"""Centralize notification dispatch, add rate-limits, dedupe, and SendPulse hardening

Revision ID: 3b0b53044068
Revises: 6d0ac8746c2e
Create Date: 2026-04-12 16:38:01.954557
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "3b0b53044068"
down_revision: Union[str, None] = "6d0ac8746c2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("is_pinned", sa.Boolean(), nullable=False))
    op.add_column(
        "notifications",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "deleted_at")
    op.drop_column("notifications", "is_pinned")
    # ### end Alembic commands ###
