# alembic/script.py.mako
"""increase_pg_version_length

Revision ID: 80be4cc31e05
Revises: 81aa97b09106
Create Date: 2026-03-22 23:15:25.602174
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "80be4cc31e05"
down_revision: Union[str, None] = "81aa97b09106"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "connections",
        "pg_version",
        existing_type=sa.VARCHAR(length=40),
        type_=sa.String(length=120),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "connections",
        "pg_version",
        existing_type=sa.String(length=120),
        type_=sa.VARCHAR(length=40),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
