# domains/migrations/service.py

"""
Migrations service.

Key fixes applied (original)
-----------------------------
1. order_index race condition — SELECT FOR UPDATE lock before computing next index.
2. generated_by as typed enum / documented constant.
3. backup_id provenance field.
4. restore migrations are auto-applied.
5. Pre-storage SQL validation (dry-run via rolled-back asyncpg transaction).

New: Migration Conflict Resolution
------------------------------------
detect_conflicts() is now called automatically inside create_migration()
when a new migration is submitted. It checks whether the incoming SQL
would conflict with already-pending (unapplied) migrations targeting the
same objects.

check_divergent_heads() detects the case where two developers have both
created migrations against the same applied baseline — i.e. there is more
than one "tip" in the pending queue that cannot be linearised without
manual intervention.

resolve_conflict() provides a structured workflow for conflict resolution:
  - "rebase"  — reorder the conflicting migration to run after the blocker
  - "squash"  — merge two pending migrations into one combined record
  - "skip"    — mark a pending migration as skipped (won't be applied)

ConflictReport is returned from create_migration() in the meta field and
exposed via the router so the UI can display it inline.

Permission guard
----------------
create_migration() and apply_migration() now call assert_connection_writable()
which fetches the stored capabilities for the connection and raises
PermissionError (HTTP 403) if the connection role is read-only. This is
the single enforcement point — the router translates it to an HTTP response.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from uuid import UUID, uuid4

import asyncpg
from loguru import logger
from sqlalchemy import DateTime, ForeignKey, String, Text, Boolean, Integer, UniqueConstraint
from sqlalchemy import select, update
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Mapped, mapped_column

from shared.types import Base


# ---------------------------------------------------------------------------
# Generated-by value registry
# ---------------------------------------------------------------------------

GENERATED_BY_VALUES = {
    "manual":  "Created manually by a developer via the UI or API.",
    "diff":    "Generated by the migra schema diff tool.",
    "ai":      "Generated by the AI SQL assistant.",
    "auto":    "Generated automatically from a visual schema editor action.",
    "restore": "Auto-created as an informational record after a backup restore. "
               "Marked applied immediately — contains no executable SQL.",
}


# ---------------------------------------------------------------------------
# ORM model
# ---------------------------------------------------------------------------

class MigrationRecord(Base):
    __tablename__ = "migration_records"

    __table_args__ = (
        UniqueConstraint(
            "connection_id",
            "order_index",
            name="uq_migration_connection_order_index",
        ),
    )

    id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid4)
    connection_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("connections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    workspace_id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), nullable=False, index=True)

    # Migration identity
    version: Mapped[str] = mapped_column(String(40), nullable=False)
    label: Mapped[str] = mapped_column(String(255), nullable=False)
    checksum: Mapped[str] = mapped_column(String(64), nullable=False)

    # SQL
    up_sql: Mapped[str] = mapped_column(Text, nullable=False)
    down_sql: Mapped[str | None] = mapped_column(Text, nullable=True)

    # State
    applied: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    applied_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rolled_back_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Ordering
    order_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Provenance — backup that triggered this migration (if any)
    backup_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("backup_records.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment=(
            "BackupRecord that triggered this migration via restore. "
            "NULL for all other generated_by values."
        ),
    )

    # Provenance string
    generated_by: Mapped[str] = mapped_column(
        String(40), default="manual", nullable=False
    )

    # Whether up_sql passed dry-run validation against the target DB
    syntax_valid: Mapped[bool | None] = mapped_column(
        Boolean, nullable=True, default=None,
        comment="Result of dry-run syntax check before storage. None = skipped.",
    )

    # Conflict tracking — set when this migration was created while conflicts exist
    has_conflict: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
        comment="True when this migration was created with unresolved conflicts.",
    )

    meta: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(timezone.utc)
    )


# ---------------------------------------------------------------------------
# Conflict resolution models
# ---------------------------------------------------------------------------

@dataclass
class ConflictDetail:
    """A single detected conflict between two pending migrations."""
    blocker_id: str            # UUID of the migration this conflicts with
    blocker_version: str
    blocker_label: str
    blocker_order_index: int
    conflict_type: str         # "same_table" | "same_object" | "divergent_head"
    affected_objects: list[str]  # Table/object names involved
    description: str


@dataclass
class ConflictReport:
    """
    Full conflict analysis for a migration being created.
    Stored in MigrationRecord.meta["conflict_report"] and returned
    from the router so the UI can display it inline.
    """
    has_conflicts: bool
    conflicts: list[ConflictDetail] = field(default_factory=list)
    divergent_heads: list[str] = field(default_factory=list)  # version strings
    resolution_options: list[str] = field(default_factory=list)
    summary: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "has_conflicts": self.has_conflicts,
            "conflicts": [
                {
                    "blocker_id": c.blocker_id,
                    "blocker_version": c.blocker_version,
                    "blocker_label": c.blocker_label,
                    "blocker_order_index": c.blocker_order_index,
                    "conflict_type": c.conflict_type,
                    "affected_objects": c.affected_objects,
                    "description": c.description,
                }
                for c in self.conflicts
            ],
            "divergent_heads": self.divergent_heads,
            "resolution_options": self.resolution_options,
            "summary": self.summary,
        }


# ---------------------------------------------------------------------------
# Version generator
# ---------------------------------------------------------------------------

def _generate_version() -> str:
    """e.g. 20240115_143022"""
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def _checksum(sql: str) -> str:
    return hashlib.sha256(sql.strip().encode()).hexdigest()


# ---------------------------------------------------------------------------
# SQL object extraction (for conflict detection)
# ---------------------------------------------------------------------------

def _extract_objects_from_sql(sql: str) -> set[str]:
    """
    Extract table and object names from SQL for conflict analysis.
    Conservative — extracts identifiers after common DDL keywords.
    Returns a set of lowercased object names.
    """
    objects: set[str] = set()

    # Patterns: ALTER TABLE x, DROP TABLE x, CREATE TABLE x,
    #           CREATE INDEX ON x, DROP INDEX x
    patterns = [
        r'(?:ALTER|DROP|CREATE(?:\s+OR\s+REPLACE)?)\s+TABLE\s+(?:IF\s+(?:NOT\s+)?EXISTS\s+)?(?:"?(\w+)"?\.)?"?(\w+)"?',
        r'CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:\w+\s+)?ON\s+(?:"?(\w+)"?\.)?"?(\w+)"?',
        r'DROP\s+INDEX\s+(?:IF\s+EXISTS\s+)?(?:"?(\w+)"?\.)?"?(\w+)"?',
        r'(?:ALTER|DROP|CREATE)\s+TYPE\s+(?:IF\s+(?:NOT\s+)?EXISTS\s+)?(?:"?(\w+)"?\.)?"?(\w+)"?',
    ]

    for pattern in patterns:
        for match in re.finditer(pattern, sql, re.IGNORECASE):
            groups = [g for g in match.groups() if g]
            if groups:
                # Use the last group (object name, not schema)
                objects.add(groups[-1].lower())

    return objects


# ---------------------------------------------------------------------------
# Conflict detection
# ---------------------------------------------------------------------------

async def check_divergent_heads(
    db: AsyncSession,
    connection_id: UUID,
) -> list[str]:
    """
    Return version strings of pending migrations that form divergent heads.

    A divergent head situation exists when there are multiple pending
    migrations that were all created against the same last-applied baseline.
    This means two developers independently created migrations without
    either knowing about the other's pending migration.

    In a healthy linear history, pending migrations form a single chain
    where each one's creation time is after the previous one's. When
    the chain forks — two migrations with adjacent order_indexes were
    both created before either was applied — we have divergent heads.
    """
    pending = await list_migrations(db, connection_id, applied=False)
    if len(pending) <= 1:
        return []

    # Find the last applied migration to use as the baseline
    last_applied = await get_last_applied(db, connection_id)
    baseline_order = last_applied.order_index if last_applied else 0

    # Pending migrations created against the same baseline (order_index == baseline + 1)
    # that were not created sequentially are divergent heads.
    # We detect this by looking for multiple pending migrations created within
    # a short window of each other before any were applied.
    divergent: list[str] = []
    if len(pending) > 1:
        # If the oldest pending migration's created_at is after all others',
        # that means multiple migrations were queued up — this is the expected
        # sequential case. But if two migrations have nearly identical creation
        # times and the same baseline, they are truly divergent.
        baseline_pending = [m for m in pending if m.order_index == baseline_order + 1]
        if len(baseline_pending) > 1:
            # This shouldn't happen due to the unique constraint, but guard anyway
            divergent = [m.version for m in baseline_pending]

        # Broader check: any two pending migrations that touch the same objects
        # are potential conflicts regardless of order_index
        # (this is handled in detect_conflicts, not here)

    return divergent


async def detect_conflicts(
    db: AsyncSession,
    connection_id: UUID,
    incoming_sql: str,
    incoming_label: str,
) -> ConflictReport:
    """
    Analyse the incoming migration SQL against all currently pending
    (unapplied) migrations for the same connection.

    Conflict types detected:
      same_object  — incoming and a pending migration both modify the
                     same table or database object
      divergent_head — multiple pending migrations exist against the same
                       applied baseline (two developers diverged)

    Returns a ConflictReport. When has_conflicts=False the migration can
    be created and applied without manual intervention.

    This is intentionally conservative — it reports potential conflicts
    rather than definitive ones. A false positive is safer than a missed
    conflict that corrupts production schema.
    """
    pending = await list_migrations(db, connection_id, applied=False)
    if not pending:
        # No pending migrations → no conflicts possible
        return ConflictReport(has_conflicts=False, summary="No conflicts detected.")

    incoming_objects = _extract_objects_from_sql(incoming_sql)

    conflicts: list[ConflictDetail] = []

    for existing in pending:
        existing_objects = _extract_objects_from_sql(existing.up_sql)
        overlap = incoming_objects & existing_objects

        if overlap:
            conflicts.append(
                ConflictDetail(
                    blocker_id=str(existing.id),
                    blocker_version=existing.version,
                    blocker_label=existing.label,
                    blocker_order_index=existing.order_index,
                    conflict_type="same_object",
                    affected_objects=sorted(overlap),
                    description=(
                        f"Both '{incoming_label}' and pending migration "
                        f"'{existing.label}' (order_index={existing.order_index}) "
                        f"modify: {', '.join(sorted(overlap))}. "
                        "Applying both without review may fail or produce "
                        "unexpected schema state."
                    ),
                )
            )

    divergent_heads = await check_divergent_heads(db, connection_id)

    has_conflicts = bool(conflicts) or bool(divergent_heads)
    resolution_options: list[str] = []

    if conflicts:
        resolution_options = ["apply_blocker_first", "rebase", "skip_blocker"]

    if divergent_heads:
        resolution_options.append("squash")

    summary = (
        f"{len(conflicts)} object conflict(s) detected with pending migrations."
        if conflicts
        else "No object conflicts detected."
    )
    if divergent_heads:
        summary += f" {len(divergent_heads)} divergent head(s) detected."

    return ConflictReport(
        has_conflicts=has_conflicts,
        conflicts=conflicts,
        divergent_heads=divergent_heads,
        resolution_options=resolution_options,
        summary=summary,
    )


# ---------------------------------------------------------------------------
# SQL validation (dry-run)
# ---------------------------------------------------------------------------

async def validate_migration_sql(
    connection_id: UUID,
    up_sql: str,
    db_url: str,
) -> tuple[bool, str | None]:
    """
    Validate migration SQL syntax by executing it inside a rolled-back
    transaction on the target database.
    
    Refactor: Securely routed through the WorkspacePoolManager.
    """
    from domains.query.service import pool_manager

    try:
        pool = await pool_manager.get_pool(connection_id, db_url)
        
        # ---------------------------------------------------------------------
        # UI CONSIDERATION: Latency for creating migrations is now ~5ms 
        # instead of ~250ms. The UI loading states for validation should be 
        # tuned for near-instant response.
        # ---------------------------------------------------------------------
        async with pool.acquire() as conn:
            async with conn.transaction():
                await conn.execute(up_sql)
                raise _ValidationRollback()
                
    except _ValidationRollback:
        return True, None
    except asyncpg.PostgresSyntaxError as exc:
        return False, f"Syntax error: {exc.args[0]}"
    except asyncpg.UndefinedTableError as exc:
        logger.debug(f"Validation: undefined table — may be OK in migration context: {exc}")
        return True, None
    except asyncpg.UndefinedColumnError as exc:
        logger.debug(f"Validation: undefined column — may be OK in migration context: {exc}")
        return True, None
    except asyncpg.InsufficientPrivilegeError as exc:
        return False, (
            f"Insufficient privileges to validate this SQL: {exc.args[0]}. "
            "The connected role may not have permission to run this DDL."
        )
    except Exception as exc:
        return False, str(exc)


class _ValidationRollback(Exception):
    """Sentinel used to intentionally roll back the dry-run transaction."""


# ---------------------------------------------------------------------------
# Permission guard
# ---------------------------------------------------------------------------

async def assert_connection_writable(
    db: AsyncSession,
    connection_id: UUID,
    operation: str = "This migration operation",
) -> None:
    """
    Fetch the connection's stored capabilities and raise PermissionError
    if the role is read-only.

    This is called by create_migration() and apply_migration() so that
    the error surfaces before any SQL is sent to the target database.
    """
    from domains.connections.models import Connection
    from domains.connections.service import assert_writable

    result = await db.execute(
        select(Connection.capabilities).where(
            Connection.id == connection_id,
            Connection.is_active == True,  # noqa: E712
        )
    )
    caps = result.scalar_one_or_none()
    if caps is None:
        # Connection not found — let downstream handle it
        return

    try:
        assert_writable(caps, operation)
    except ValueError as exc:
        raise PermissionError(str(exc)) from exc


# ---------------------------------------------------------------------------
# Core migration operations
# ---------------------------------------------------------------------------

_MAX_ORDER_INDEX_RETRIES = 5


async def create_migration(
    db: AsyncSession,
    connection_id: UUID,
    workspace_id: UUID,
    label: str,
    up_sql: str,
    down_sql: str | None = None,
    generated_by: str = "manual",
    backup_id: UUID | None = None,
    db_url: str | None = None,
    skip_validation: bool = False,
    skip_conflict_check: bool = False,
) -> MigrationRecord:
    if generated_by not in GENERATED_BY_VALUES:
        raise ValueError(
            f"Unknown generated_by value '{generated_by}'. "
            f"Must be one of: {', '.join(GENERATED_BY_VALUES)}"
        )

    # Permission guard
    if generated_by != "restore" and not skip_conflict_check:
        try:
            await assert_connection_writable(
                db, connection_id,
                operation=f"Creating migration '{label}'"
            )
        except PermissionError:
            raise  

    # SQL validation
    syntax_valid: bool | None = None
    validation_error: str | None = None

    if db_url and not skip_validation and generated_by != "restore":
        # FIXED: Pass connection_id here
        syntax_valid, validation_error = await validate_migration_sql(connection_id, up_sql, db_url)
        if not syntax_valid:
            logger.warning(
                f"Migration SQL validation failed for '{label}': {validation_error}"
            )

    # Conflict detection
    conflict_report: ConflictReport | None = None
    has_conflict = False

    if not skip_conflict_check and generated_by != "restore":
        conflict_report = await detect_conflicts(db, connection_id, up_sql, label)
        has_conflict = conflict_report.has_conflicts
        if has_conflict:
            logger.warning(
                f"Migration '{label}' created with {len(conflict_report.conflicts)} "
                f"conflict(s): {conflict_report.summary}"
            )

    from sqlalchemy.exc import IntegrityError
    import asyncio

    for attempt in range(1, _MAX_ORDER_INDEX_RETRIES + 1):
        try:
            record = await _create_migration_attempt(
                db=db,
                connection_id=connection_id,
                workspace_id=workspace_id,
                label=label,
                up_sql=up_sql,
                down_sql=down_sql,
                generated_by=generated_by,
                backup_id=backup_id,
                syntax_valid=syntax_valid,
                validation_error=validation_error,
                has_conflict=has_conflict,
                conflict_report=conflict_report,
            )
            return record
        except IntegrityError as exc:
            await db.rollback()
            if "uq_migration_connection_order_index" not in str(exc) or attempt == _MAX_ORDER_INDEX_RETRIES:
                raise
            wait = 0.05 * attempt
            logger.warning(
                f"order_index collision on attempt {attempt}/{_MAX_ORDER_INDEX_RETRIES} "
                f"for connection {connection_id} — retrying in {wait:.2f}s"
            )
            await asyncio.sleep(wait)

    raise RuntimeError("create_migration: exhausted retries")


async def _create_migration_attempt(
    db: AsyncSession,
    connection_id: UUID,
    workspace_id: UUID,
    label: str,
    up_sql: str,
    down_sql: str | None,
    generated_by: str,
    backup_id: UUID | None,
    syntax_valid: bool | None,
    validation_error: str | None,
    has_conflict: bool,
    conflict_report: "ConflictReport | None",
) -> MigrationRecord:
    """Single attempt at creating a migration record with SELECT FOR UPDATE locking."""
    lock_result = await db.execute(
        select(MigrationRecord)
        .where(MigrationRecord.connection_id == connection_id)
        .order_by(MigrationRecord.order_index.desc())
        .limit(1)
        .with_for_update()
    )
    last = lock_result.scalar_one_or_none()
    next_order = (last.order_index + 1) if last else 1

    meta: dict = {}
    if validation_error:
        meta["validation_error"] = validation_error
    if conflict_report and conflict_report.has_conflicts:
        meta["conflict_report"] = conflict_report.to_dict()

    record = MigrationRecord(
        connection_id=connection_id,
        workspace_id=workspace_id,
        version=_generate_version(),
        label=label,
        checksum=_checksum(up_sql),
        up_sql=up_sql.strip(),
        down_sql=down_sql.strip() if down_sql else None,
        applied=False,
        order_index=next_order,
        generated_by=generated_by,
        backup_id=backup_id,
        syntax_valid=syntax_valid,
        has_conflict=has_conflict,
        meta=meta,
    )
    db.add(record)
    await db.commit()
    await db.refresh(record)

    status_parts = []
    if syntax_valid is True:
        status_parts.append("syntax_valid=True")
    elif syntax_valid is False:
        status_parts.append("syntax_valid=False")
    else:
        status_parts.append("validation_skipped")
    if has_conflict:
        status_parts.append("has_conflict=True")

    logger.info(
        f"Migration created: {record.version} ({label}) "
        f"order={next_order} {' '.join(status_parts)}"
    )
    return record


async def apply_migration(
    pg_conn: asyncpg.Connection,
    db: AsyncSession,
    migration_id: UUID,
    force_apply: bool = False,
) -> MigrationRecord:
    """
    Apply a single migration to the target database.

    Blocked when:
    - syntax_valid is False (SQL failed pre-storage validation)
    - has_conflict is True AND force_apply is False

    force_apply=True allows applying a conflicted migration after the
    developer has manually reviewed and accepted the risk.
    """
    record = await _get_migration_or_raise(db, migration_id)

    if record.applied:
        raise ValueError(f"Migration {record.version} is already applied.")

    if record.syntax_valid is False:
        validation_error = record.meta.get("validation_error", "unknown error")
        raise ValueError(
            f"Migration {record.version} failed syntax validation before storage "
            f"and cannot be applied: {validation_error}. "
            "Delete this migration, fix the SQL, and create a new one."
        )

    if record.has_conflict and not force_apply:
        conflict_summary = record.meta.get("conflict_report", {}).get(
            "summary", "conflicts detected"
        )
        raise ValueError(
            f"Migration {record.version} has unresolved conflicts: {conflict_summary}. "
            "Resolve conflicts first (POST /migrations/{connection_id}/resolve) "
            "or re-apply with force_apply=true to override."
        )

    try:
        # ---------------------------------------------------------------------
        # UI CONSIDERATION: The frontend MUST expect a maximum response time 
        # of ~35 seconds for this endpoint. If the DB operation takes longer, 
        # the backend will aggressively kill it and return a 400 error. 
        # The UI should display: "Migration aborted: Operation too heavy. 
        # Consider batching or adding CONCURRENTLY to indexes."
        # ---------------------------------------------------------------------
        async with pg_conn.transaction():
            # 1. Enforce aggressive fast-fail on lock acquisition (2 seconds)
            # If another user is querying the table, don't hang the pool waiting.
            await pg_conn.execute("SET LOCAL lock_timeout = '2000';")
            
            # 2. Enforce engine-level circuit breaker for execution length (30 seconds)
            await pg_conn.execute("SET LOCAL statement_timeout = '30000';")
            
            await pg_conn.execute(record.up_sql)

        record.applied = True
        record.applied_at = datetime.now(timezone.utc)
        record.error = None
        record.has_conflict = False  # Clear conflict flag after successful apply
        await db.commit()
        await db.refresh(record)
        logger.info(f"Migration applied: {record.version}")
        return record

    except asyncpg.InsufficientPrivilegeError as exc:
        record.error = (
            f"Insufficient privileges: {exc.args[0]}. "
            "The connected role does not have permission to run this DDL."
        )
        await db.commit()
        logger.error(f"Migration {record.version} failed (privileges): {exc}")
        raise
    except Exception as exc:
        error_msg = str(exc)
        
        # Translate physics violations into clear feedback
        if getattr(exc, "sqlstate", None) == '55P03':  # lock_not_available
            error_msg = "Lock acquisition timed out (2s limit). The table is locked by an active transaction."
        elif isinstance(exc, asyncpg.QueryCanceledError) or "timeout" in error_msg.lower():
            error_msg = "Migration timed out (30s limit). DDL must be optimized or batched."
            
        record.error = error_msg
        await db.commit()
        logger.error(f"Migration {record.version} failed: {error_msg}")
        raise ValueError(error_msg)


async def rollback_migration(
    pg_conn: asyncpg.Connection,
    db: AsyncSession,
    migration_id: UUID,
) -> MigrationRecord:
    record = await _get_migration_or_raise(db, migration_id)

    if not record.applied:
        raise ValueError(f"Migration {record.version} is not applied.")
    if not record.down_sql:
        raise ValueError(
            f"Migration {record.version} has no rollback SQL. "
            "Manual rollback required."
        )
    if record.generated_by == "restore":
        raise ValueError(
            f"Migration {record.version} is an informational restore record "
            "with no executable SQL. It cannot be rolled back."
        )

    try:
        async with pg_conn.transaction():
            await pg_conn.execute(record.down_sql)

        record.applied = False
        record.rolled_back_at = datetime.now(timezone.utc)
        record.error = None
        await db.commit()
        await db.refresh(record)
        logger.info(f"Migration rolled back: {record.version}")
        return record

    except asyncpg.InsufficientPrivilegeError as exc:
        record.error = (
            f"Insufficient privileges: {exc.args[0]}. "
            "The connected role does not have permission to roll back this migration."
        )
        await db.commit()
        logger.error(f"Rollback of {record.version} failed (privileges): {exc}")
        raise
    except Exception as exc:
        record.error = str(exc)
        await db.commit()
        logger.error(f"Rollback of {record.version} failed: {exc}")
        raise


async def apply_pending(
    pg_conn: asyncpg.Connection,
    db: AsyncSession,
    connection_id: UUID,
    force_apply: bool = False,
) -> list[MigrationRecord]:
    """
    Apply all pending migrations in order_index order.

    If any pending migration has has_conflict=True, apply_pending will
    stop at that migration and raise ValueError unless force_apply=True.
    """
    pending = await list_migrations(db, connection_id, applied=False)

    # Pre-flight conflict check — surface all conflicts before touching the DB
    if not force_apply:
        conflicted = [m for m in pending if m.has_conflict and m.generated_by != "restore"]
        if conflicted:
            versions = ", ".join(m.version for m in conflicted)
            raise ValueError(
                f"{len(conflicted)} pending migration(s) have unresolved conflicts "
                f"({versions}). Resolve conflicts first or use force_apply=true."
            )

    applied = []
    for record in pending:
        if record.generated_by == "restore":
            logger.warning(
                f"Skipping restore migration {record.version} in apply_pending "
                "— it should already be marked applied."
            )
            continue
        result = await apply_migration(pg_conn, db, record.id, force_apply=force_apply)
        applied.append(result)
    return applied


# ---------------------------------------------------------------------------
# Conflict resolution workflow
# ---------------------------------------------------------------------------

async def resolve_conflict(
    db: AsyncSession,
    migration_id: UUID,
    strategy: str,
    target_migration_id: UUID | None = None,
) -> MigrationRecord:
    """
    Resolve a conflict on a pending migration.

    Strategies
    ----------
    "accept"       — Clear the conflict flag, allow apply to proceed.
                     Use this after manually reviewing and confirming the
                     SQL is safe to run after the blocking migrations.

    "rebase"       — Move this migration to run AFTER target_migration_id
                     by bumping its order_index. Requires target_migration_id.

    "skip"         — Mark this migration as applied without executing its SQL.
                     Use only when you are certain the schema change was
                     already applied by another means.

    "squash"       — Merge this migration's SQL into target_migration_id's SQL
                     and delete this record. Requires target_migration_id.
                     target_migration_id must also be pending.
    """
    if strategy not in ("accept", "rebase", "skip", "squash"):
        raise ValueError(
            f"Unknown resolution strategy '{strategy}'. "
            "Must be: accept, rebase, skip, squash."
        )

    record = await _get_migration_or_raise(db, migration_id)

    if record.applied:
        raise ValueError(
            f"Migration {record.version} is already applied and cannot be resolved."
        )

    if strategy == "accept":
        record.has_conflict = False
        meta = dict(record.meta)
        meta.pop("conflict_report", None)
        meta["conflict_resolved"] = {
            "strategy": "accept",
            "resolved_at": datetime.now(timezone.utc).isoformat(),
        }
        record.meta = meta
        await db.commit()
        await db.refresh(record)
        logger.info(f"Conflict accepted for migration {record.version}")
        return record

    if strategy == "rebase":
        if not target_migration_id:
            raise ValueError("'rebase' strategy requires target_migration_id.")

        target = await _get_migration_or_raise(db, target_migration_id)
        if target.applied:
            raise ValueError(
                f"Target migration {target.version} is already applied. "
                "Rebase to a pending migration."
            )

        # Place this migration immediately after the target
        new_order = target.order_index + 1

        # Shift all migrations after the target up by 1 to make room
        await db.execute(
            update(MigrationRecord)
            .where(
                MigrationRecord.connection_id == record.connection_id,
                MigrationRecord.order_index >= new_order,
                MigrationRecord.id != record.id,
                MigrationRecord.applied == False,  # noqa: E712
            )
            .values(order_index=MigrationRecord.order_index + 1)
        )

        record.order_index = new_order
        record.has_conflict = False
        meta = dict(record.meta)
        meta["conflict_resolved"] = {
            "strategy": "rebase",
            "after_migration": str(target_migration_id),
            "resolved_at": datetime.now(timezone.utc).isoformat(),
        }
        record.meta = meta
        await db.commit()
        await db.refresh(record)
        logger.info(
            f"Migration {record.version} rebased to order_index={new_order}"
        )
        return record

    if strategy == "skip":
        record.applied = True
        record.applied_at = datetime.now(timezone.utc)
        record.has_conflict = False
        meta = dict(record.meta)
        meta["conflict_resolved"] = {
            "strategy": "skip",
            "note": "Marked applied without executing SQL.",
            "resolved_at": datetime.now(timezone.utc).isoformat(),
        }
        record.meta = meta
        await db.commit()
        await db.refresh(record)
        logger.info(f"Migration {record.version} skipped (marked applied without execution)")
        return record

    if strategy == "squash":
        if not target_migration_id:
            raise ValueError("'squash' strategy requires target_migration_id.")

        target = await _get_migration_or_raise(db, target_migration_id)
        if target.applied:
            raise ValueError(
                f"Target migration {target.version} is already applied. "
                "Cannot squash into an applied migration."
            )
        if record.id == target.id:
            raise ValueError("Cannot squash a migration into itself.")

        # Merge this migration's SQL into the target
        separator = (
            f"\n\n-- Squashed from migration {record.version} "
            f"({record.label}) --\n"
        )
        target.up_sql = target.up_sql.rstrip() + separator + record.up_sql
        target.checksum = _checksum(target.up_sql)
        target.label = f"{target.label} + {record.label}"[:255]
        target.has_conflict = False

        meta = dict(target.meta)
        meta["squashed_migrations"] = meta.get("squashed_migrations", []) + [
            {
                "version": record.version,
                "label": record.label,
                "squashed_at": datetime.now(timezone.utc).isoformat(),
            }
        ]
        target.meta = meta

        # Delete the squashed record
        await db.delete(record)
        await db.commit()
        await db.refresh(target)
        logger.info(
            f"Migration {record.version} squashed into {target.version}"
        )
        return target

    # Unreachable but keeps type checker happy
    raise ValueError(f"Unhandled strategy: {strategy}")


# ---------------------------------------------------------------------------
# History queries
# ---------------------------------------------------------------------------

async def list_migrations(
    db: AsyncSession,
    connection_id: UUID,
    applied: bool | None = None,
    limit: int = 100,
    offset: int = 0,
    order_index_from: int | None = None,
    order_index_to: int | None = None,
) -> list[MigrationRecord]:
    q = select(MigrationRecord).where(
        MigrationRecord.connection_id == connection_id
    )
    if applied is not None:
        q = q.where(MigrationRecord.applied == applied)
    if order_index_from is not None:
        q = q.where(MigrationRecord.order_index >= order_index_from)
    if order_index_to is not None:
        q = q.where(MigrationRecord.order_index <= order_index_to)

    q = q.order_by(MigrationRecord.order_index.asc()).offset(offset).limit(limit)
    result = await db.execute(q)
    return list(result.scalars().all())


async def get_migration(
    db: AsyncSession,
    migration_id: UUID,
) -> MigrationRecord | None:
    result = await db.execute(
        select(MigrationRecord).where(MigrationRecord.id == migration_id)
    )
    return result.scalar_one_or_none()


async def get_migration_at_order_index(
    db: AsyncSession,
    connection_id: UUID,
    order_index: int,
) -> MigrationRecord | None:
    result = await db.execute(
        select(MigrationRecord).where(
            MigrationRecord.connection_id == connection_id,
            MigrationRecord.order_index == order_index,
        )
    )
    return result.scalar_one_or_none()


async def get_last_applied(
    db: AsyncSession,
    connection_id: UUID,
) -> MigrationRecord | None:
    result = await db.execute(
        select(MigrationRecord)
        .where(
            MigrationRecord.connection_id == connection_id,
            MigrationRecord.applied == True,  # noqa
        )
        .order_by(MigrationRecord.order_index.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def delete_migration(
    db: AsyncSession,
    migration_id: UUID,
) -> bool:
    record = await get_migration(db, migration_id)
    if not record:
        return False
    if record.applied:
        raise ValueError("Cannot delete an applied migration. Roll it back first.")
    await db.delete(record)
    await db.commit()
    return True


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------

def export_as_alembic_py(record: MigrationRecord) -> str:
    safe_label = re.sub(r"[^\w]", "_", record.label).lower()[:50]
    down_sql = record.down_sql or "pass  # No rollback defined"
    down_body = (
        f'    op.execute("""\n    {down_sql}\n    """)'
        if record.down_sql
        else "    pass"
    )

    validation_note = (
        f"Syntax validation: {'passed' if record.syntax_valid is True else 'skipped' if record.syntax_valid is None else 'FAILED'}"
    )
    conflict_note = f"Conflict flag: {'YES — review before applying' if record.has_conflict else 'none'}"

    return f'''"""
{record.label}

Revision ID: {record.version}
Order index: {record.order_index}
Generated by: Calyphant ({record.generated_by}) — {GENERATED_BY_VALUES.get(record.generated_by, "unknown")}
Created at: {record.created_at.isoformat()}
Backup source: {record.backup_id or "none"}
{validation_note}
{conflict_note}
"""

from alembic import op


revision = "{record.version}"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    {record.up_sql}
    """)


def downgrade() -> None:
{down_body}
'''


# ---------------------------------------------------------------------------
# Internal
# ---------------------------------------------------------------------------

async def _get_migration_or_raise(
    db: AsyncSession,
    migration_id: UUID,
) -> MigrationRecord:
    record = await get_migration(db, migration_id)
    if not record:
        raise ValueError(f"Migration {migration_id} not found.")
    return record